### ISSUE TITLE
Lost Agents

### ISSUE THREAD

**Issue by lukebarnard1** [suegy/IA-AgentScape-Rover#1]
Agents are sometimes lost when changing scenarios using the monitor. 

To repeat this bug, do the following:
1. Start agentscape server using lib/boot.jar
2. Run config editor and set the configuration to include 10 non-monitor agents
3. Hit CTRL+R in the rover config editor
4. Focus on the monitor and wait for all agents to be loaded
5. Repeatedly change the scenario and click "Select Scenario"
6. Eventually, agents will be lost from the table view at the bottom of the monitor, indicating that they have failed to remain connected to the server

**Comment by lukebarnard1** [comment]
Possibly related exception:

```
Agent_1_13 - Got KernelException in connect()
org.iids.aos.kernel.exception.ConnectionSetupException: peer has too many pending virtual connections at the moment
    at org.iids.aos.kernel.mux.ConnectionPort.eventOpenNack(ConnectionPort.java:488) ~[aos-kernel-2.0.0.jar:na]
    at org.iids.aos.kernel.mux.Mux.receivedOpenNack(Mux.java:1085) ~[aos-kernel-2.0.0.jar:na]
    at org.iids.aos.kernel.mux.Mux.access$800(Mux.java:75) ~[aos-kernel-2.0.0.jar:na]
    at org.iids.aos.kernel.mux.Mux$BaseConnectionReaderThread.msgReceived(Mux.java:646) ~[aos-kernel-2.0.0.jar:na]
    at org.iids.aos.kernel.mux.Mux$LoopbackBaseConnectionReaderThread.run(Mux.java:462) ~[aos-kernel-2.0.0.jar:na]
```

**Comment by suegy** [comment]
This specific error stack is related but not causing agents to drop. 
The original issue mentioned was resolved in the latest commit.

**Comment by suegy** [comment]
It seems the problem is still present and needs further evaluation and feedback to pinpoint
